---
name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
        run: mvn -B package --file pom.xml && ls -l

      - uses: "marvinpinto/action-automatic-releases@latest"
        id: release
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-dev"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE
            *.jar
      - name : Get file name
        id: get-file-name
        run: |
          echo "::set-output name=JAR_FILE::$(cd ./target && find . -type f \( -iname "*.jar" ! -iname "original*.jar" ! -iname "*SHADED.jar" \))"
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./target/${{ steps.get-file-name.outputs.JAR_FILE }}
          asset_name: ${{ steps.get-file-name.outputs.JAR_FILE }}
          asset_content_type: application/java-archive